SELECT *
FROM games;

-- FOR FINDING OUT THE MOST POPULAR GAMES IN THE TABLE . BECAUSE MOST POPULAR
-- GAMES WILL HAVE MORE NUMBER OF PLAYERS.

SELECT MAX(players) , title
FROM games;

-- FOR FINDING OUT THE COUNTS OF ALL THE DIFFERENT PROGRAMMING LANGUAGES
-- USED FOR GAME DEVELOPING

SELECT language , COUNT(*)
FROM games
GROUP BY language;

-- FOR FINDING OUT THE AVERAGE METASCORES FOR EACH GENRE

SELECT AVG(metascore) , title , genre
FROM games
GROUP BY genre
ORDER BY AVG (metascore);